Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Carbon.RangeEditor:Plugin:
            resource: resource://Carbon.RangeEditor/Public/Plugin.js
            attributes:
              type: 'module'
        stylesheets:
          Carbon.RangeEditor:Plugin:
            resource: resource://Carbon.RangeEditor/Public/Plugin.css
